name: CI
on:  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
          mkdir /tmp/build
          cd /tmp/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/ $GITHUB_WORKSPACE

    - name: Build package
      run: |
	  pwd
	  cmake --build . --target cmakespark

