name: CI
on: push

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    strategy:
      matrix:
        env:
        - { CMAKE_BUILD_TYPE: "Debug" }
        - { CMAKE_BUILD_TYPE: "Release" }
    env: ${{ matrix.env }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure
      run: |
          mkdir /tmp/build
          cd /tmp/build
          cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/tmp/ $GITHUB_WORKSPACE

    - name: Build
      run: cmake --build /tmp/build --target all

    - name: Test
      run: cmake --build /tmp/build --target runtests

    - name: Package
      run: cmake --build /tmp/build --target cmakespark

    - name: Upload cmakespark.zip
      uses: actions/upload-artifact@v1
      with:
        name: cmakespark.zip
        path: /tmp/build/cmakespark.zip

