name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.cfg.os }}
    name:    ${{ matrix.cfg.name }} (${{ matrix.cfg.build_type }})
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - { os: ubuntu-latest,  name: GCC,     cc: gcc,   cxx: g++,     platform: x64, build_type: Debug }
        - { os: ubuntu-latest,  name: GCC,     cc: gcc,   cxx: g++,     platform: x64, build_type: Release }
        - { os: ubuntu-latest,  name: Clang,   cc: clang, cxx: clang++, platform: x64, build_type: Debug }
        - { os: ubuntu-latest,  name: Clang,   cc: clang, cxx: clang++, platform: x64, build_type: Release }
        - { os: windows-latest, name: Windows, cc: cl,    cxx: cl,      platform: x32, build_type: Debug }
        - { os: windows-latest, name: Windows, cc: cl,    cxx: cl,      platform: x64, build_type: Release }

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure
      run: |
          mkdir /tmp/build
          cd /tmp/build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.cfg.build_type }} -DCMAKE_INSTALL_PREFIX=/tmp/ $GITHUB_WORKSPACE

    - name: Build
      run: cmake --build /tmp/build --target all

    - name: Test
      run: cmake --build /tmp/build --target runtests

    - name: Package
      run: cmake --build /tmp/build --target cmakespark

    - name: Upload cmakespark.zip
      uses: actions/upload-artifact@v1
      with:
        name: cmakespark.zip
        path: /tmp/build/cmakespark.zip

