name: CI
on:  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
    - uses: actions/checkout@v2

    - name: Configure
      run: |
          mkdir /tmp/build
          cd /tmp/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/ $GITHUB_WORKSPACE

    - name: Build package
      run: |
          cd /tmp/build
          cmake --build . --target cmakespark
    
    - name: Upload cmakespark.zip
      uses: actions/upload-artifact@v1
      with:
        name: cmakespark.zip
        path: /tmp/build/cmakespark.zip

